name: Test APP

on: push

env:
  NODE_VERSION: 20.10.0
  IP_ADDRESS: "5.35.99.66"

jobs:
  test-application:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Test Application
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: "npm"
      - run: |
          npm install
          npm run build
  create-deployment-artifacts:
    needs: test-application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build App Artifacts
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: "npm"
      - run: |
          touch .env
          echo SUPABASE_URL="https://jteofxqllbykhvfqnfnp.supabase.co" >> .env
          echo SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0ZW9meHFsbGJ5a2h2ZnFuZm5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTU4MTI5MDUsImV4cCI6MjAxMTM4ODkwNX0._y7JdVJ14mMoe3Tt6prNcx84CVbu4JodYVG86XNFz4s" >> .env
          echo RELEASE_VERSION=${GITHUB_REF} >> .env
          echo GITHUB_SHA=${{ github.sha }} >> .env
          npm i
          npm run build
          cp .env .output/server/.env
          tar -czf "${GITHUB_SHA}".tar.gz .output
      - name: Store app-artifacts for distribution
        uses: actions/upload-artifact@v3
        with:
          name: app-artifacts
          path: ${{ github.sha }}.tar.gz
  prepare-release-on-servers:
    needs: create-deployment-artifacts
    name: "Prepare release on INT server"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: app-artifacts
      - name: Upload app-artifacts
        uses: appleboy/scp-action@master
        with:
          host: ${{env.IP_ADDRESS}}
          port: "22"
          username: "root"
          key: ${{ secrets.OMG_SECRET }}
          source: ${{ github.sha }}.tar.gz
          target: /var/www/html/artifacts

      - name: Extract archive and create directories
        uses: appleboy/ssh-action@master
        env:
          GITHUB_SHA: ${{ github.sha }}

        with:
          host: ${{env.IP_ADDRESS}}
          username: "root"
          key: ${{ secrets.OMG_SECRET }}
          port: "22"
          envs: GITHUB_SHA
          script: |
            mkdir -p "/var/www/html/releases/${GITHUB_SHA}"
            tar xzf /var/www/html/artifacts/${GITHUB_SHA}.tar.gz -C "/home/zhukovka"
            rm -rf /var/www/html/artifacts/${GITHUB_SHA}.tar.gz
  activate-release:
    name: "Activate release"
    runs-on: ubuntu-latest
    needs: prepare-release-on-servers
    steps:
      - name: Activate Release
        uses: appleboy/ssh-action@master
        env:
          RELEASE_PATH: /var/www/html/releases/${{ github.sha }}
          ACTIVE_RELEASE_PATH: /home/zhukovka
        with:
          host: ${{env.IP_ADDRESS}}
          username: "root"
          key: ${{ secrets.OMG_SECRET }}
          port: "22"
          envs: RELEASE_PATH,ACTIVE_RELEASE_PATH
          script: |
            ln -s -n -f $RELEASE_PATH $ACTIVE_RELEASE_PATH
            systemctl restart zhukovka
            chown -R www-data:www-data ${RELEASE_PATH}
